apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "8087"
  EUREKA_URL: "http://eureka-service:8761/eureka/"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  EMAIL_SENDER: "fiap.oficina@gmail.com"
  MANAGEMENT_HEALTH_MAIL_ENABLED: "false"
  AWS_REGION: "us-east-1"
  AWS_ENDPOINT_URL: ""
