apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
type: Opaque
stringData:
  RABBITMQ_USERNAME: "oficina"
  RABBITMQ_PASSWORD: "oficina"
  EMAIL_USERNAME: "fiap.oficina@gmail.com"
  EMAIL_PASSWORD: "change-me-app-password"
